//ERROR
export const ERROR = 'ERROR'
export const OBJ_ERROR_TIME_OUT = {status: 'ERROR_TIME_OUT', mensaje: 'Error de conexión a internet.'}
//USUARIO
export const USUARIO_GUARDAR = 'USUARIO_GUARDAR'
export const USUARIOS_OBTENER = 'USUARIOS_OBTENER'
export const USUARIO_OBTENER_OAUTH = 'USUARIO_OBTENER_OAUTH'
export const USUARIO_OBTENER = 'USUARIO_OBTENER'
//PERFIL
export const PERFILES_OBTENER = 'PERFILES_OBTENER'
export const PERFIL_OBTENER = 'PERFIL_OBTENER'
export const PERFIL_GUARDAR = 'PERFIL_GUARDAR'

//ESTADO CIVIL
export const ESTADOCIVIL_OBTENER = 'ESTADOCIVIL_OBTENER'
//DOCUMENTO IDENTIDAD
export const DOCUMENTOIDENTIDAD_OBTENER = 'DOCUMENTOIDENTIDAD_OBTENER'
//SEXO
export const SEXO_OBTENER = 'SEXO_OBTENER'
//UBICACION
export const TIPO_DIRECCION_OBTENER = 'TIPO_DIRECCION_OBTENER'
//PAIS
export const PAIS_OBTENER = 'PAIS_OBTENER'
export const PAIS_NACIMIENTO_OBTENER = 'PAIS_NACIMIENTO_OBTENER'
//DEPARTAMENTO
export const DEPARTAMENTO_OBTENER = 'DEPARTAMENTO_OBTENER'
export const DEPARTAMENTO_NACIMIENTO_OBTENER = 'DEPARTAMENTO_NACIMIENTO_OBTENER'
//PROVINCIA
export const PROVINCIA_OBTENER = 'PROVINCIA_OBTENER'
export const PROVINCIA_NACIMIENTO_OBTENER = 'PROVINCIA_NACIMIENTO_OBTENER'
//DISTRITO
export const DISTRITO_OBTENER = 'DISTRITO_OBTENER'
export const DISTRITO_NACIMIENTO_OBTENER = 'DISTRITO_NACIMIENTO_OBTENER'

//CLIENTE
export const CLIENTE_GUARDAR = 'CLIENTE_GUARDAR'
export const CLIENTE_ACTUALIZAR = 'CLIENTE_ACTUALIZAR'
export const CLIENTE_OBTENER = 'CLIENTE_OBTENER'
export const CLIENTES_OBTENER = 'CLIENTES_OBTENER'
export const PUESTOS_LABORALES_GUARDAR = 'PUESTOS_LABORALES_GUARDAR'
export const PUESTOS_LABORALES_ACTUALIZAR = 'PUESTOS_LABORALES_ACTUALIZAR'
export const PUESTO_LABORAL_OBTENER = 'PUESTO_LABORAL_OBTENER'

export const JOBPOSITIONS_GET = 'JOBPOSITIONS_GET'
export const JOBPOSITION_CANDIDATES_GET = 'JOBPOSITION_CANDIDATES_GET'
export const JOBPOSITION_CANDIDATE_ADD = 'JOBPOSITION_CANDIDATE_ADD'
export const JOBPOSITION_CANDIDATE_DELETE = 'JOBPOSITION_CANDIDATE_DELETE'
//CANDIDATO
export const CANDIDATES_GET = 'CANDIDATES_GET'

export const CANDIDATO_GUARDAR = 'CANDIDATO_GUARDAR'
export const CANDIDATO_OBTENER = 'CANDIDATO_OBTENER'
export const CANDIDATOS_OBTENER = 'CANDIDATOS_OBTENER'
export const CANDIDATO_REGISTRADO_VALIDAR = 'CANDIDATO_REGISTRADO_VALIDAR'
export const CANDIDATO_TESTPSICOLOGICO_RECLUTADOR_GUARDAR = 'CANDIDATO_TESTPSICOLOGICO_RECLUTADOR_GUARDAR'
export const CANDIDATO_TESTPSICOLOGICO_GUARDAR = 'CANDIDATO_TESTPSICOLOGICO_GUARDAR'
export const CANDIDATO_TESTPSICOLOGICOS_PREGUNTAS_OBTENER = 'CANDIDATO_TESTPSICOLOGICOS_PREGUNTAS_OBTENER'
export const CANDIDATO_TESTPSICOLOGICOS_FINALIZADO_VALIDAR = 'CANDIDATO_TESTPSICOLOGICOS_FINALIZADO_VALIDAR'
export const CANDIDATO_TESTPSICOLOGICOS_RESPUESTAS_OBTENER = 'CANDIDATO_TESTPSICOLOGICOS_RESPUESTAS_OBTENER'
export const CANDIDATO_TESTPSICOLOGICOS_RESULTADO_GRAFICO_OBTENER = 'CANDIDATO_TESTPSICOLOGICOS_RESULTADO_GRAFICO_OBTENER'
export const CANDIDATO_TESTPSICOLOGICOS_OBTENER = 'CANDIDATO_TESTPSICOLOGICOS_OBTENER'
export const CANDIDATO_RESPUESTAS_OBTENER = 'CANDIDATO_RESPUESTAS_OBTENER'
export const CANDIDATO_TESTPSICOLOGICOSDETALLE_OBTENER = 'CANDIDATO_TESTPSICOLOGICOSDETALLE_OBTENER'
export const CANDIDATO_GUARDAR_RESPUESTA = 'CANDIDATO_GUARDAR_RESPUESTA'

export const CANDIDATO_PUESTO_LABORAL_OBTENER = 'CANDIDATO_PUESTO_LABORAL_OBTENER'
//TESTPSICOLOGICOS
export const TESTPSICOLOGICOS_OBTENER = 'TESTPSICOLOGICOS_OBTENER'
export const TESTPSICOLOGICO_PREGUNTAS_OBTENER = 'TESTPSICOLOGICO_PREGUNTAS_OBTENER'
export const TESTPSICOLOGICO_PARTES_OBTENER = 'TESTPSICOLOGICO_PARTES_OBTENER'
//INFORME TESTPSICOLOGICOS
export const INFORME_GENERAR = 'INFORME_GENERAR'
export const INTERPRETACION_OBTENER = 'INTERPRETACION_OBTENER'

//RECLUTADOR
export const RECLUTADOR_GUARDAR = 'RECLUTADOR_GUARDAR'
export const RECLUTADOR_OBTENER = 'RECLUTADOR_OBTENER'
export const RECLUTADORES_OBTENER = 'RECLUTADORES_OBTENER'
export const RECLUTADOR_NOTIFICAR = 'RECLUTADOR_NOTIFICAR'

//SELECTIONPROCESS
export const SELECTIONPROCESS_GET = 'SELECTIONPROCESS_GET'

//CANDIDATOAPRECIACION
export const CANDIDATOAPRECIACION_GET = 'CANDIDATOAPRECIACION_GET'
export const CANDIDATOAPRECIACION_ADD = 'CANDIDATOAPRECIACION_ADD'